services:
  app:
    build: .
    env_file:
      - .env.development
      - .env
    ports:
      - '3000:80'
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:18
    env_file: .env
    environment:
      POSTGRES_USER: thankful
      PGUSER: thankful
    volumes:
      # - "./db-data:/var/lib/postgresql"
      - "db-data:/var/lib/postgresql"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "thankful"]
      retries: 5
      start_period: 30s
      start_interval: 2s
      
volumes:
  db-data: {}